<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
	$attribute_code="custom_option_show"; // attribute with text value
	$description_attribute = $product->getResource()->getAttribute($attribute_code);
	$description_attribute_value = $description_attribute ->getFrontend()->getValue($product);
 ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <!-- Custom Input Field -->
		<?php if($description_attribute_value == "Yes"){ ?>
			<div class="amasty-textoverimages-block" style="text-align: <?= $this->getTextAlign()?>">
				<div class="main_class">
					<div class="jersey_nlbl"> Enter Jersey Number </div>
					<div class="input_Jerseyno"><input type="text" name="cloudways[jersey_number]" size="50" id="jersey_number"  maxlength="255" class="jersy_no"  placeholder="Enter Jersey Number"></input></div>
				</div>
				<div class="main_class">
					<div class="u_nlbl"> Enter Name (12 chars)</div>
					<div class="input_Jerseyname"><input type="text" name="cloudways[jersey_name] size="50" id="jersey_name" maxlength="255" class="jersy_name" placeholder="Enter Name (12 chars)"></input></div>
				</div>
			</div>
		<?php }  ?>
         <!-- Custom Input Field -->
        <br>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>